#!/bin/sh

[ -r ./conf ] && . ./conf

# note: maybe use ibus start or ibus-daemon instead and start ibus-ui-gtk3 separately
# $([ "$XDG_SESSION_TYPE" = "wayland" ] && echo "--enable-wayland-im")
exec chpst -e "$TURNSTILE_ENV_DIR" /usr/libexec/ibus-ui-gtk3 \
  --enable-wayland-im --exec-daemon --daemon-args \
  "--panel disable $([ "$XDG_SESSION_TYPE" = "x11" ] && echo "--xim") $OPTS" 2>&1
