[font]
size = 11
hinting = "full"
edging = "antialias"

[font.features]
"Monaspace Neon NF" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08"]
"Monaspace Radon NF" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08"]
"Monaspace Krypton NF" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08"]
"Monaspace Xenon NF" = ["+calt", "+liga", "+dlig", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08"]

[[font.normal]]
family = "Monaspace Neon NF"
style = "Thin"

[[font.italic]]
family = "Monaspace Radon NF"
style = "Light"
slant = "Italic"

[[font.bold]]
family = "Monaspace Krypton NF"
style = "Bold"

[[font.bold_italic]]
family = "Monaspace Xenon NF"
style = "Bold"
slant = "Italic"

# fallback for glyphs
[[font.normal]]
family = "Symbols Nerd Font"
