[config]

[templates.nvim]
input_path = "~/.config/noctalia/templates/neovim.lua"
output_path = "~/.config/nvim/lua/noctalia.lua"
post_hook = "pkill -SIGUSR1 nvim"

[templates.opencode]
input_path = "~/.config/noctalia/templates/opencode.json"
output_path = "~/.config/opencode/themes/noctalia.json"

[templates.zellij]
input_path = "~/.config/noctalia/templates/zellij.kdl"
output_path = "~/.config/zellij/themes/noctalia.kdl"
post_hook = "touch ~/.config/zellij/config.kdl"
